[package]
name = "hello-lambda"
authors = ["Ryo Munakata <afpacket@gmail.com>"]
version = "0.0.1"
edition = "2018"

[dependencies]
lambda_runtime = "0.2"
lambda_http = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
